[[constraint]]
  version = "v1.10.1"
  name = "github.com/pulumi/pulumi"

[[constraint]]
  version = "v2.0.0"
  name = "github.com/pulumi/pulumi-azure"

[prune]
  go-tests = true
  unused-packages = true
